CREATE DATABASE IF NOT EXISTS transcendence_db;

CREATE TABLE IF NOT EXISTS user (
	id INT AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(50) UNIQUE NOT NULL,
	email VARCHAR(100) UNIQUE NOT NULL,
	password TEXT NOT NULL,
	avatar TEXT DEFAULT NULL,
	twoFA_enabled BOOLEAN DEFAULT FALSE,
	twoFA_secret TEXT DEFAULT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS matches (
	id INT AUTO_INCREMENT PRIMARY KEY,
	is_pong_game BOOLEAN DEFAULT FALSE,
	player1 INT NOT NULL,
	player2 INT DEFAULT NULL,
	winner INT DEFAULT NULL,
	score1 INT NOT NULL,
	score2 INT NOT NULL,
	played_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (player1) REFERENCES users(id) ON DELETE CASCADE,
	FOREIGN KEY (player2) REFERENCES users(id) ON DELETE CASCADE,
	FOREIGN KEY (winner) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS friends (
	user1 INT NOT NULL,
	user2 INT NOT NULL,
	status ENUM('pending', 'accepted', 'blocked') DEFAULT 'pending',
	PRIMARY KEY (user1, user2),
	FOREIGN KEY (user1) REFERENCES users(id) ON DELETE CASCADE,
	FOREIGN KEY (user2) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;

