# Étape de build
FROM node:23.10-alpine AS builder
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . .
RUN npm run build

# Étape de production avec serveur statique
FROM node:23.10-alpine AS production
WORKDIR /app

COPY --from=builder /app/dist ./dist
RUN npm install -g serve

ENV NODE_ENV=production
EXPOSE 5173

# Serve sur le bon port
CMD [ "serve", "-s", "-l", "5173", "dist" ]


