# Étape de build
FROM node:23.10-alpine AS builder
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . .
RUN npm run build

# Étape de production avec vite preview
FROM node:23.10-alpine AS production
WORKDIR /app

COPY --from=builder /app/dist ./dist
RUN npm install -g vite

ENV NODE_ENV=production
CMD ["vite", "preview", "--host", "--port", "5173"]

