filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/caddy/access.log
    json.keys_under_root: true
    json.add_error_key: true
    json.message_key: log

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "caddy-logs-%{+yyyy.MM.dd}"
