FROM node:23.10-alpine AS base

ARG APP_DIR

WORKDIR /app

# Assure-toi que ceci fonctionne
COPY ${APP_DIR}/package*.json ./

RUN npm install --production

FROM node:23.10-alpine AS build
ARG APP_DIR
WORKDIR /app
COPY ${APP_DIR}/ .
RUN npm run build

FROM node:23.10-alpine AS final
WORKDIR /app
COPY --from=base /app/node_modules ./node_modules
COPY --from=build /app/dist ./dist
COPY ${APP_DIR}/package*.json ./

CMD ["node", "dist/server.js"]

