


# Étape de base : installation des dépendances
FROM node:23.10-alpine AS base

WORKDIR /app
ARG APP_DIR

COPY ./${APP_DIR}/package*.json ./

ENV NODE_ENV=development

RUN npm ci

FROM base AS final

WORKDIR /app

COPY ./${APP_DIR}/ ./

CMD ["npm", "run", "dev"]
